import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Language = 'en' | 'ar';

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.markets': 'Markets',
    'nav.about': 'About',
    'nav.blogs': 'Blogs',
    'nav.tradingTools': 'Trading Tools',
    'nav.contactUs': 'Contact Us',
    'nav.login': 'Log in',
    'nav.signup': 'Sign up',
    'market.forex': 'Forex',
    'market.commodities': 'Commodities',
    'market.stocks': 'Stocks',
    'market.etfs': 'ETFs',
    'market.crypto': 'Cryptocurrencies',
    'market.indices': 'Indices',
    'hero.title.before': 'Trade smarter with ',
    'hero.title.accent': 'real-time',
    'hero.title.after': ' market insights',
    'hero.subtitle': 'Access global markets, advanced charting tools, and AI-powered analytics — all in one platform built for modern traders.',
    'hero.getStarted': 'Get Started',
    'hero.learnMore': 'Learn More',
    'hero.stat1.value': '0.0',
    'hero.stat1.label': 'PIP SPREADS*',
    'hero.stat2.value': '1:1000',
    'hero.stat2.label': 'LEVERAGE',
    'hero.stat3.value': '0.01',
    'hero.stat3.label': 'MICRO LOT TRADING',
    'hero.stat4.value': '+2250',
    'hero.stat4.label': 'TRADABLE INSTRUMENTS',
    'hero.stat5.value': '24/7',
    'hero.stat5.label': 'DEDICATED SUPPORT',
    'instruments.tag': 'Instruments',
    'instruments.title.line1': 'Trade over 2,250+',
    'instruments.title.accent': 'instruments',
    'instruments.title.line2': 'worldwide',
    'instruments.subtitle': 'Access stocks, crypto, forex, commodities, and indices — all from one powerful platform designed for modern traders.',
    'instruments.cta': 'Explore Markets',
    'features.title.line1': 'Why traders choose',
    'features.title.accent': 'Equitix',
    'features.subtitle': 'Everything you need to trade with confidence — all in one platform.',
    'features.card1.title': 'Free Signals',
    'features.card1.desc': 'Get real-time trading signals from expert analysts delivered straight to your platform — completely free.',
    'features.card2.title': '24/7 Support',
    'features.card2.desc': 'Our dedicated support team is available around the clock to help you with any questions or issues.',
    'features.card3.title': '0% Commission',
    'features.card3.desc': 'Trade with zero commission fees on all instruments. Keep more of your profits with every trade.',
    'features.card4.title': 'Fast Execution',
    'features.card4.desc': 'Ultra-low latency order execution under 50ms ensures you never miss a market opportunity.',
    'features.card5.title': 'One Click Trading',
    'features.card5.desc': 'Execute trades instantly with a single click. No confirmations, no delays — just fast action.',
    'features.card6.title': 'Refer & Earn',
    'features.card6.desc': 'Invite friends to Equitix and earn rewards for every successful referral. The more you share, the more you earn.',
    'accounts.title.line1': 'Choose your',
    'accounts.title.accent': 'account',
    'accounts.subtitle': 'Start trading with the plan that fits your goals. Upgrade anytime as you grow.',
    'accounts.popular': 'Most Popular',
    'accounts.min': 'min. deposit',
    'accounts.cta': 'Open Account',
    'accounts.viewAll': 'View All Accounts',
    'accounts.silver.name': 'Silver',
    'accounts.silver.price': '$250',
    'accounts.silver.desc': 'Perfect for beginners exploring the markets with essential trading tools.',
    'accounts.gold.name': 'Gold',
    'accounts.gold.price': '$500',
    'accounts.gold.desc': 'For active traders who want premium tools and dedicated support.',
    'accounts.platinum.name': 'Platinum',
    'accounts.platinum.price': '$1,000',
    'accounts.platinum.desc': 'Full VIP experience with the tightest spreads and exclusive perks.',
    'accounts.b.spreads.silver': 'Spreads from 1.2 pips',
    'accounts.b.spreads.gold': 'Spreads from 0.6 pips',
    'accounts.b.spreads.platinum': 'Spreads from 0.0 pips',
    'accounts.b.leverage.silver': 'Leverage up to 1:200',
    'accounts.b.leverage.gold': 'Leverage up to 1:500',
    'accounts.b.leverage.platinum': 'Leverage up to 1:1000',
    'accounts.b.instruments': '2,250+ instruments',
    'accounts.b.support.basic': '24/5 email support',
    'accounts.b.support.priority': '24/7 priority support',
    'accounts.b.support.vip': '24/7 VIP support + direct line',
    'accounts.b.signals': 'Free trading signals',
    'accounts.b.manager': 'Dedicated account manager',
    'accounts.b.vps': 'Free VPS hosting',
    'accounts.b.cashback': 'Cashback on every trade',
    'referral.tag': 'Refer & Earn',
    'referral.title.line1': 'Invite friends, earn',
    'referral.title.accent': '50%',
    'referral.title.line2': 'of their deposit',
    'referral.subtitle': 'Share your referral link and earn 50% of every friend\'s first deposit as a cash reward. No limits, no caps.',
    'referral.reward.line1': 'Of their first deposit',
    'referral.reward.line2': 'Credited instantly to your account',
    'referral.step1.title': 'Share Your Link',
    'referral.step1.desc': 'Get your unique referral link from your dashboard and share it with friends.',
    'referral.step2.title': 'Friend Deposits',
    'referral.step2.desc': 'When your friend signs up and makes their first deposit, you both win.',
    'referral.step3.title': 'Get Rewarded',
    'referral.step3.desc': '50% of their deposit is credited to your account instantly. Withdraw or trade it.',
    'referral.cta': 'Start Referring',
    'assets.title': 'Trade over 1,500+ assets',
    'assets.title.accent': 'worldwide',
    'assets.subtitle': 'Access stocks, crypto, forex, commodities, and indices — all from one powerful platform.',
    'assets.stat1': 'Tradable Assets',
    'assets.stat2': 'Asset Classes',
    'assets.stat3': 'Market Access',
    'bento.tag': 'Why Equitix',
    'bento.title.line1': 'Built for traders who',
    'bento.title.accent': 'demand',
    'bento.title.line2': 'more',
    'bento.subtitle': 'Professional-grade tools, lightning execution, and enterprise security — unified in one powerful platform.',
    'bento.card1.title': '1,500+ Instruments',
    'bento.card1.desc': 'Trade stocks, crypto, forex, commodities, and indices — all from one platform.',
    'bento.card2.title': 'Advanced Analytics',
    'bento.card2.desc': 'AI-powered insights and charting tools to stay ahead of the market.',
    'bento.card3.title': 'Bank-Grade Security',
    'bento.card3.desc': 'Your funds and data are protected with enterprise-level encryption.',
    'bento.card4.title': 'Powerful APIs',
    'bento.card4.desc': 'Build custom strategies with our developer-friendly trading APIs.',
    'blog.title': 'Latest from our',
    'blog.title.accent': 'blog',
    'blog.subtitle': 'Insights, strategies, and market analysis to sharpen your trading edge.',
    'blog.readMore': 'Read more',
    'blog.viewAll': 'View All Articles',
    'blog.post1.cat': 'Market Analysis',
    'blog.post1.title': 'How to Read Candlestick Patterns Like a Pro Trader',
    'blog.post1.desc': 'Master the art of candlestick analysis and learn to identify key reversal and continuation patterns that drive market movements.',
    'blog.post2.cat': 'Crypto',
    'blog.post2.title': 'Bitcoin Halving 2025: What It Means for Your Portfolio',
    'blog.post2.desc': 'Understand the impact of Bitcoin halving events on price action and discover strategies to position your portfolio ahead of time.',
    'blog.post3.cat': 'Strategy',
    'blog.post3.title': 'Risk Management: The One Skill Every Trader Needs',
    'blog.post3.desc': 'Learn proven risk management techniques used by professional traders to protect capital and maximize long-term returns.',
    'steps.tag': 'Get Started',
    'steps.title.line1': 'Start trading in',
    'steps.title.accent': 'three',
    'steps.title.line2': 'easy steps',
    'steps.subtitle': 'Open your account, fund it, and start trading — all in just a few minutes.',
    'steps.step1.title': 'Create Your Account',
    'steps.step1.desc': 'Sign up in minutes with your name, email, and phone number. Quick verification gets you trading-ready.',
    'steps.step2.title': 'Fund Your Account',
    'steps.step2.desc': 'Choose from multiple deposit methods and select the amount that fits your trading goals.',
    'steps.step3.title': 'Start Trading',
    'steps.step3.desc': 'Access global markets, place trades with advanced order types, and manage your portfolio in real time.',
    'steps.cta': 'Open Free Account',
    'faq.title.line1': 'Frequently asked',
    'faq.title.accent': 'questions',
    'faq.subtitle': 'Everything you need to know before you start trading with Equitix.',
    'faq.cta': 'Contact Support',
    'faq.q1': 'What is Equitix and how does it work?',
    'faq.a1': 'Equitix is a modern trading platform that gives you access to global markets including forex, stocks, commodities, crypto, and indices. Sign up, fund your account, and start trading with professional-grade tools.',
    'faq.q2': 'What is the minimum deposit to start trading?',
    'faq.a2': 'You can start trading with as little as $500. We offer multiple deposit tiers so you can choose the amount that best fits your trading strategy and goals.',
    'faq.q3': 'Is my money safe with Equitix?',
    'faq.a3': 'Absolutely. We use bank-grade encryption, segregated client accounts, and are regulated by top-tier financial authorities. Your funds are always protected.',
    'faq.q4': 'What markets can I trade on Equitix?',
    'faq.a4': 'You can trade forex pairs, global stocks, commodities like gold and oil, cryptocurrencies, ETFs, and major market indices — all from a single account.',
    'faq.q5': 'How fast are order executions?',
    'faq.a5': 'Our infrastructure delivers ultra-low latency execution, typically under 50 milliseconds. You get real-time market data and instant order fills across all instruments.',
    'faq.q6': 'Does Equitix offer a mobile app?',
    'faq.a6': 'Yes. Our mobile app is available on iOS and Android with full trading capabilities, real-time charts, push notifications for signals, and portfolio management on the go.',
    'faq.q7': 'How do I withdraw my funds?',
    'faq.a7': 'Withdrawals are processed within 24 hours. You can withdraw via bank transfer, credit card, or e-wallets. There are no hidden fees on withdrawals.',
    'contact.title': 'Get in',
    'contact.title.accent': 'touch',
    'contact.subtitle': 'Have a question or need help? Fill out the form and our team will get back to you shortly.',
    'contact.firstName': 'First Name',
    'contact.lastName': 'Last Name',
    'contact.email': 'Email Address',
    'contact.phone': 'Phone Number',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.info.title': 'Contact Information',
    'contact.info.subtitle': 'Reach out to us directly or follow us on social media.',
    'contact.info.email': 'support@equitix.com',
    'contact.info.phone': '+966 800 123 4567',
    'contact.info.social': 'Follow Us',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.markets': 'الأسواق',
    'nav.about': 'حول',
    'nav.blogs': 'المدونات',
    'nav.tradingTools': 'أدوات التداول',
    'nav.contactUs': 'اتصل بنا',
    'nav.login': 'تسجيل الدخول',
    'nav.signup': 'إنشاء حساب',
    'market.forex': 'فوركس',
    'market.commodities': 'السلع',
    'market.stocks': 'الأسهم',
    'market.etfs': 'صناديق المؤشرات',
    'market.crypto': 'العملات الرقمية',
    'market.indices': 'المؤشرات',
    'hero.title.before': 'تداول بذكاء مع ',
    'hero.title.accent': 'رؤى سوقية',
    'hero.title.after': ' فورية',
    'hero.subtitle': 'اصل إلى الأسواق العالمية وأدوات الرسوم البيانية المتقدمة والتحليلات المدعومة بالذكاء الاصطناعي — كل ذلك في منصة واحدة مصممة للمتداولين العصريين.',
    'hero.getStarted': 'ابدأ الآن',
    'hero.learnMore': 'اعرف المزيد',
    'hero.stat1.value': '0.0',
    'hero.stat1.label': 'سبريد بالنقاط*',
    'hero.stat2.value': '1:1000',
    'hero.stat2.label': 'رافعة مالية',
    'hero.stat3.value': '0.01',
    'hero.stat3.label': 'تداول لوت مايكرو',
    'hero.stat4.value': '+2250',
    'hero.stat4.label': 'أداة مالية قابلة للتداول',
    'hero.stat5.value': '24/7',
    'hero.stat5.label': 'دعم فني مخصص',
    'instruments.tag': 'الأدوات المالية',
    'instruments.title.line1': 'تداول أكثر من 2,250+',
    'instruments.title.accent': 'أداة مالية',
    'instruments.title.line2': 'حول العالم',
    'instruments.subtitle': 'اوصل إلى الأسهم والعملات الرقمية والفوركس والسلع والمؤشرات — كل ذلك من منصة واحدة مصممة للمتداولين العصريين.',
    'instruments.cta': 'استكشف الأسواق',
    'features.title.line1': 'لماذا يختار المتداولون',
    'features.title.accent': 'إكويتكس',
    'features.subtitle': 'كل ما تحتاجه للتداول بثقة — في منصة واحدة.',
    'features.card1.title': 'إشارات مجانية',
    'features.card1.desc': 'احصل على إشارات تداول فورية من محللين خبراء مباشرة إلى منصتك — مجاناً بالكامل.',
    'features.card2.title': 'دعم على مدار الساعة',
    'features.card2.desc': 'فريق الدعم المخصص لدينا متاح على مدار الساعة لمساعدتك في أي أسئلة أو مشاكل.',
    'features.card3.title': '0% عمولة',
    'features.card3.desc': 'تداول بدون رسوم عمولة على جميع الأدوات. احتفظ بمزيد من أرباحك مع كل صفقة.',
    'features.card4.title': 'تنفيذ سريع',
    'features.card4.desc': 'تنفيذ أوامر بزمن استجابة منخفض للغاية أقل من 50 مللي ثانية لضمان عدم تفويت أي فرصة.',
    'features.card5.title': 'تداول بنقرة واحدة',
    'features.card5.desc': 'نفّذ الصفقات فوراً بنقرة واحدة. بدون تأكيدات، بدون تأخير — فقط تنفيذ سريع.',
    'features.card6.title': 'أحِل واكسب',
    'features.card6.desc': 'ادعُ أصدقاءك إلى إكويتكس واكسب مكافآت عن كل إحالة ناجحة. كلما شاركت أكثر، كسبت أكثر.',
    'accounts.title.line1': 'اختر حسابك',
    'accounts.title.accent': 'المناسب',
    'accounts.subtitle': 'ابدأ التداول بالخطة التي تناسب أهدافك. يمكنك الترقية في أي وقت.',
    'accounts.popular': 'الأكثر شيوعاً',
    'accounts.min': 'حد أدنى للإيداع',
    'accounts.cta': 'افتح حساب',
    'accounts.viewAll': 'عرض جميع الحسابات',
    'accounts.silver.name': 'فضي',
    'accounts.silver.price': '$250',
    'accounts.silver.desc': 'مثالي للمبتدئين الذين يستكشفون الأسواق بأدوات تداول أساسية.',
    'accounts.gold.name': 'ذهبي',
    'accounts.gold.price': '$500',
    'accounts.gold.desc': 'للمتداولين النشطين الذين يريدون أدوات متميزة ودعم مخصص.',
    'accounts.platinum.name': 'بلاتيني',
    'accounts.platinum.price': '$1,000',
    'accounts.platinum.desc': 'تجربة VIP كاملة مع أضيق السبريد وامتيازات حصرية.',
    'accounts.b.spreads.silver': 'سبريد من 1.2 نقطة',
    'accounts.b.spreads.gold': 'سبريد من 0.6 نقطة',
    'accounts.b.spreads.platinum': 'سبريد من 0.0 نقطة',
    'accounts.b.leverage.silver': 'رافعة مالية حتى 1:200',
    'accounts.b.leverage.gold': 'رافعة مالية حتى 1:500',
    'accounts.b.leverage.platinum': 'رافعة مالية حتى 1:1000',
    'accounts.b.instruments': '+2,250 أداة مالية',
    'accounts.b.support.basic': 'دعم بالبريد 24/5',
    'accounts.b.support.priority': 'دعم أولوية 24/7',
    'accounts.b.support.vip': 'دعم VIP 24/7 + خط مباشر',
    'accounts.b.signals': 'إشارات تداول مجانية',
    'accounts.b.manager': 'مدير حساب مخصص',
    'accounts.b.vps': 'استضافة VPS مجانية',
    'accounts.b.cashback': 'كاشباك على كل صفقة',
    'referral.tag': 'أحِل واكسب',
    'referral.title.line1': 'ادعُ أصدقاءك واكسب',
    'referral.title.accent': '50%',
    'referral.title.line2': 'من إيداعهم',
    'referral.subtitle': 'شارك رابط الإحالة الخاص بك واكسب 50% من أول إيداع لكل صديق كمكافأة نقدية. بدون حدود.',
    'referral.reward.line1': 'من أول إيداع لهم',
    'referral.reward.line2': 'يُضاف فوراً إلى حسابك',
    'referral.step1.title': 'شارك رابطك',
    'referral.step1.desc': 'احصل على رابط الإحالة الفريد من لوحة التحكم وشاركه مع أصدقائك.',
    'referral.step2.title': 'صديقك يودع',
    'referral.step2.desc': 'عندما يسجل صديقك ويقوم بأول إيداع، تربحان معاً.',
    'referral.step3.title': 'احصل على مكافأتك',
    'referral.step3.desc': '50% من إيداعهم يُضاف إلى حسابك فوراً. اسحبه أو تداول به.',
    'referral.cta': 'ابدأ الإحالة',
    'assets.title': 'تداول أكثر من 1,500 أصل',
    'assets.title.accent': 'حول العالم',
    'assets.subtitle': 'اوصل إلى الأسهم والعملات الرقمية والفوركس والسلع والمؤشرات — كل ذلك من منصة واحدة.',
    'assets.stat1': 'أصل قابل للتداول',
    'assets.stat2': 'فئات أصول',
    'assets.stat3': 'وصول للأسواق',
    'bento.tag': 'لماذا إكويتكس',
    'bento.title.line1': 'صُمم للمتداولين الذين',
    'bento.title.accent': 'يطلبون',
    'bento.title.line2': 'المزيد',
    'bento.subtitle': 'أدوات احترافية، تنفيذ فائق السرعة، وأمان على مستوى المؤسسات — كل ذلك في منصة واحدة.',
    'bento.card1.title': '+1,500 أداة مالية',
    'bento.card1.desc': 'تداول الأسهم والعملات الرقمية والفوركس والسلع والمؤشرات — كل ذلك من منصة واحدة.',
    'bento.card2.title': 'تحليلات متقدمة',
    'bento.card2.desc': 'رؤى مدعومة بالذكاء الاصطناعي وأدوات رسوم بيانية للبقاء في الصدارة.',
    'bento.card3.title': 'أمان بمستوى البنوك',
    'bento.card3.desc': 'أموالك وبياناتك محمية بتشفير على مستوى المؤسسات.',
    'bento.card4.title': 'واجهات برمجة قوية',
    'bento.card4.desc': 'أنشئ استراتيجيات مخصصة باستخدام واجهات برمجة التداول.',
    'blog.title': 'آخر مقالات',
    'blog.title.accent': 'المدونة',
    'blog.subtitle': 'رؤى واستراتيجيات وتحليلات سوقية لتعزيز مهاراتك في التداول.',
    'blog.readMore': 'اقرأ المزيد',
    'blog.viewAll': 'عرض جميع المقالات',
    'blog.post1.cat': 'تحليل السوق',
    'blog.post1.title': 'كيف تقرأ أنماط الشموع اليابانية كمتداول محترف',
    'blog.post1.desc': 'أتقن فن تحليل الشموع اليابانية وتعلم تحديد أنماط الانعكاس والاستمرار الرئيسية التي تحرك الأسواق.',
    'blog.post2.cat': 'عملات رقمية',
    'blog.post2.title': 'تنصيف البيتكوين 2025: ماذا يعني لمحفظتك',
    'blog.post2.desc': 'افهم تأثير أحداث تنصيف البيتكوين على حركة الأسعار واكتشف استراتيجيات لتجهيز محفظتك مسبقاً.',
    'blog.post3.cat': 'استراتيجية',
    'blog.post3.title': 'إدارة المخاطر: المهارة الأساسية لكل متداول',
    'blog.post3.desc': 'تعلم تقنيات إدارة المخاطر المثبتة التي يستخدمها المتداولون المحترفون لحماية رأس المال وتعظيم العوائد.',
    'steps.tag': 'ابدأ الآن',
    'steps.title.line1': 'ابدأ التداول في',
    'steps.title.accent': 'ثلاث',
    'steps.title.line2': 'خطوات سهلة',
    'steps.subtitle': 'افتح حسابك، موّله، وابدأ التداول — كل ذلك في دقائق معدودة.',
    'steps.step1.title': 'أنشئ حسابك',
    'steps.step1.desc': 'سجّل في دقائق باستخدام اسمك وبريدك الإلكتروني ورقم هاتفك. التحقق السريع يجعلك جاهزاً للتداول.',
    'steps.step2.title': 'موّل حسابك',
    'steps.step2.desc': 'اختر من طرق إيداع متعددة وحدد المبلغ الذي يناسب أهدافك في التداول.',
    'steps.step3.title': 'ابدأ التداول',
    'steps.step3.desc': 'اوصل إلى الأسواق العالمية، نفّذ صفقات بأنواع أوامر متقدمة، وأدر محفظتك في الوقت الفعلي.',
    'steps.cta': 'افتح حساب مجاني',
    'faq.title.line1': 'الأسئلة الشائعة',
    'faq.title.accent': 'والأجوبة',
    'faq.subtitle': 'كل ما تحتاج معرفته قبل أن تبدأ التداول مع إكويتكس.',
    'faq.cta': 'تواصل مع الدعم',
    'faq.q1': 'ما هي إكويتكس وكيف تعمل؟',
    'faq.a1': 'إكويتكس هي منصة تداول حديثة تمنحك الوصول إلى الأسواق العالمية بما في ذلك الفوركس والأسهم والسلع والعملات الرقمية والمؤشرات. سجّل، موّل حسابك، وابدأ التداول بأدوات احترافية.',
    'faq.q2': 'ما هو الحد الأدنى للإيداع لبدء التداول؟',
    'faq.a2': 'يمكنك بدء التداول بمبلغ 500 دولار فقط. نوفر مستويات إيداع متعددة لتختار المبلغ الذي يناسب استراتيجيتك وأهدافك.',
    'faq.q3': 'هل أموالي آمنة مع إكويتكس؟',
    'faq.a3': 'بالتأكيد. نستخدم تشفيراً بمستوى البنوك، وحسابات عملاء منفصلة، ونخضع لرقابة هيئات مالية عليا. أموالك محمية دائماً.',
    'faq.q4': 'ما الأسواق التي يمكنني التداول فيها؟',
    'faq.a4': 'يمكنك تداول أزواج الفوركس والأسهم العالمية والسلع مثل الذهب والنفط والعملات الرقمية وصناديق المؤشرات والمؤشرات الرئيسية — كل ذلك من حساب واحد.',
    'faq.q5': 'ما مدى سرعة تنفيذ الأوامر؟',
    'faq.a5': 'بنيتنا التحتية توفر تنفيذاً بزمن استجابة منخفض للغاية، عادةً أقل من 50 مللي ثانية. تحصل على بيانات سوق حية وتنفيذ فوري للأوامر.',
    'faq.q6': 'هل توفر إكويتكس تطبيق جوال؟',
    'faq.a6': 'نعم. تطبيقنا متاح على iOS و Android مع إمكانيات تداول كاملة ورسوم بيانية حية وإشعارات فورية وإدارة المحفظة أثناء التنقل.',
    'faq.q7': 'كيف أسحب أموالي؟',
    'faq.a7': 'تتم معالجة عمليات السحب خلال 24 ساعة. يمكنك السحب عبر التحويل البنكي أو بطاقة الائتمان أو المحافظ الإلكترونية. لا توجد رسوم خفية.',
    'contact.title': 'تواصل',
    'contact.title.accent': 'معنا',
    'contact.subtitle': 'هل لديك سؤال أو تحتاج مساعدة؟ املأ النموذج وسيتواصل فريقنا معك قريباً.',
    'contact.firstName': 'الاسم الأول',
    'contact.lastName': 'اسم العائلة',
    'contact.email': 'البريد الإلكتروني',
    'contact.phone': 'رقم الهاتف',
    'contact.subject': 'الموضوع',
    'contact.message': 'الرسالة',
    'contact.send': 'إرسال الرسالة',
    'contact.info.title': 'معلومات التواصل',
    'contact.info.subtitle': 'تواصل معنا مباشرة أو تابعنا على وسائل التواصل الاجتماعي.',
    'contact.info.email': 'support@equitix.com',
    'contact.info.phone': '+966 800 123 4567',
    'contact.info.social': 'تابعنا',
  },
} as const;

type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: TranslationKey): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
